version: "3"

services:
  test-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5434:5432"
    volumes:
      - psql-test:/var/lib/postgresql/data

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    working_dir: /src
    environment:
      - app_TEST_DATABASE_URL=postgresql+asyncpg://user:password@test-db:5432/postgres
      - app_ENVIRONMENT=TESTING
      - app_ALLOWED_CORS_ORIGINS=["http://localhost:3000"]
      - app_BASE_URL=/api/v1
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
    depends_on:
      - test-db
    command: ["bash", "-c", "alembic upgrade head && pytest"]

volumes:
  psql-test: null