version: "3"

services:
  test-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5434:5432"
    volumes:
      - psql-test:/var/lib/postgresql/data

  test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/src
    working_dir: /src
    environment:
      - app_ENVIRONMENT=TESTING
    depends_on:
      - test-db
    command: ["bash", "-c", "alembic upgrade head && pytest"]

volumes:
  psql-test: null