name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup and Run tests
        run: docker-compose -f docker-compose-test.yaml up --build -d

  # cleanup:
  #   name: Cleanup
  #   run: docker-compose -f docker-compose-test.yaml down --remove-orphans
